apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-guestbook
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: guestbook-dev
          - env: prod
            namespace: guestbook-prod
            templatePatch: |-
              spec:
                source:
                  helm:
                    valueFiles:
                      - values.yaml
                      - values-production.yaml

  template:
    metadata:
      name: helm-guestbook-{{env}}
      labels:
        app.kubernetes.io/name: helm-guestbook
        env: "{{env}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/anmolharness/argocd-example-apps.git
        targetRevision: master
        path: helm-guestbook
        helm:
          releaseName: helm-guestbook
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: anmol-harness
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
